---
# Run with ansible-playbook <filename> -k
#   (make sure to add the IPs of machines you want to manage to /etc/ansible/hosts first)

- hosts: 10.74.244.55
  gather_facts: False
  user: vagrant
#  become: yes

  tasks:
  #- name: Install Python 2
  #raw: test -e /usr/bin/python || (apt-get update && apt-get install -y python)
  - name: Create Vagrant user
    user: 
      name: vagrant
      shell: /bin/bash
      state: present
      comment: Ansilbe_adm
      group: sudo
      expires: -1

  - name: Fancy way of doing authorized_keys
    authorized_key:
      user:  vagrant
      exclusive: no
      key: "{{ lookup('file', '/home/vagrant/.ssh/id_rsa.pub') }}"


    #  - name: Create /root/.ssh
    #file: path=/root/.ssh state=directory mode=0700

    #- name: Create /root/.ssh/authorized_keys from our local ssh pubkey
    #lineinfile: dest=/root/.ssh/authorized_keys line="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

